travis:
  secure:
    BINSTAR_TOKEN: DkARKY65iKbmDli47eyjVy0LuoP4ovNA+DyRXKcXG7rOZt45/Nl798+Xl0B/jgGRm+Uf7/ohCw0RzlcYLPFxwQXAgjKi+F+KIg574zhGrVV/7VywtWVf+UQZieYEsh2SoHCYu1izXAxXnlr8RQl7dW53+/H+RQDyRMVpHiufzi5ajP7hm6yPiq3Qiq3fH+fPfH1dwJeAWKS4IRRawZy9VYxOn4rZd9gUTyCZwU/BHrrkl8y2PuWPMAaIc9I/5XCTBdiJUPFs0yCm6wkyUFy3JA4th6Hd75+F0b38Jj/roHXV+dTyTig7Zp991+sJN8nOVWJSLtMxb2UpNnN7nkRLZ6rXO0dvkYMWWcGX2H0F2Jduw6Wim59JYLpDvR2bOAZyoEbAFeyCkpLKM7V84uBU/2PYOaXGqvks3vlAKnzSRCY/4WxtjoW6ZxbVlejS2LCc4FreM0NB8nT9joNbI5ryvEgwfZiMyaFwj7WdB2TtT/9ndmQ/nycMJXudHBnlTnssgaIRyKthHalERX+Wh7/ilLA9hEdMNeJs9zm3Iiv00iqs9lL4BmWoRiOn1FB9pI4CvAkJbig26XFkROCC7ML81KijU75pQhMV95Pq9ipIc5hIrJmH+r3q+UfryLE5rovIgWwfTJwNv0drklqUkzb7abLlrJEoSE1A7X0oENHhzwg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
